<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robotScriptModel" nsURI="http://www.example.org/robotScriptModel"
    nsPrefix="robotScriptModel">
  <eClassifiers xsi:type="ecore:EClass" name="EntryPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="funs" upperBound="-1" eType="#//FunDef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//AnyType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//SimpleVarDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyType" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDecl" abstract="true" interface="true"
      eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//AnyType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//AnyType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assign" abstract="true" interface="true"
      eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignVar" eSuperTypes="#//Assign">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//VarDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetSpeed" eSuperTypes="#//Assign">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//UnitCast"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Unit">
    <eLiterals name="m" literal="m"/>
    <eLiterals name="dm" value="1" literal="dm"/>
    <eLiterals name="cm" value="2" literal="cm"/>
    <eLiterals name="mm" value="3" literal="mm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimBoolExpr" abstract="true" interface="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Add" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Movement" abstract="true" interface="true"
      eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rotation" eSuperTypes="#//Movement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Linear" eSuperTypes="#//Movement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//UnitCast"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dir" lowerBound="1" eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true" interface="true"
      eSuperTypes="#//PrimExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lit" eSuperTypes="#//PrimExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetSpeed" eSuperTypes="#//PrimExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//UnitCast"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ref" eSuperTypes="#//PrimExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" lowerBound="1" eType="#//VarDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunCall" eSuperTypes="#//Statement #//PrimExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fun" lowerBound="1" eType="#//FunDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimExpr" abstract="true" interface="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//PrimBoolExpr #//UnExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Compare" eSuperTypes="#//PrimBoolExpr #//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mul" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Neg" eSuperTypes="#//UnExpr #//PrimExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmts" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleVarDecl" eSuperTypes="#//VarDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarDeclInit" eSuperTypes="#//VarDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStmt" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmt" lowerBound="1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStmt" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmt1" lowerBound="1" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmt2" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnStmt" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinExpr" abstract="true" interface="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr1" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr2" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnExpr" abstract="true" interface="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//PrimExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Time" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Distance" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//UnitCast"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitCast">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="#//Unit"
        defaultValueLiteral="mm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="Forward"/>
    <eLiterals name="Sideways" value="1"/>
  </eClassifiers>
</ecore:EPackage>
