/*
 * generated by Xtext 2.32.0
 */
package robotScriptXText;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RobotScriptStandaloneSetup extends RobotScriptStandaloneSetupGenerated {

	public static void doSetup() {
		new RobotScriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
