/*
 * generated by Xtext 2.32.0
 */
package robotScriptXText.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import robotScriptXText.parser.antlr.internal.InternalRobotScriptParser;
import robotScriptXText.services.RobotScriptGrammarAccess;

public class RobotScriptParser extends AbstractAntlrParser {

	@Inject
	private RobotScriptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRobotScriptParser createParser(XtextTokenStream stream) {
		return new InternalRobotScriptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EntryPoint";
	}

	public RobotScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RobotScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
