/*
 * generated by Xtext 2.32.0
 */
package robotScriptXText.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RobotScriptAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("robotScriptXText/parser/antlr/internal/InternalRobotScript.tokens");
	}
}
