/*
 * generated by Xtext 2.32.0
 */
package robotScript.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotScriptScopeProvider extends DelegatingScopeProvider {
}
